# Generated by Django 4.1.3 on 2023-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0003_alter_otp_otp_alter_otp_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='punch_in',
            field=models.TimeField(default='14:12:28', editable=False),
        ),
    ]
