# Generated by Django 4.1.3 on 2023-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0004_alter_otp_otp_alter_otp_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='punch_in',
            field=models.TimeField(default='14:31:08', editable=False),
        ),
    ]
