# Generated by Django 4.1.3 on 2023-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0005_alter_otp_otp_alter_otp_punch_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='punch_in',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='ankit@gmail.com', editable=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='first_name',
            field=models.CharField(default='ankit', editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='in_time',
            field=models.TimeField(default='18:46:38', editable=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='last_name',
            field=models.CharField(default='ankit', editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default='ankit', editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
