# Generated by Django 4.1.3 on 2023-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0007_alter_otp_email_alter_otp_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='count',
            field=models.SmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='in_time',
            field=models.TimeField(default='21:30:14', editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
