# Generated by Django 4.1.3 on 2023-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0008_otp_count_alter_otp_in_time_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='count',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='in_time',
            field=models.TimeField(default='21:47:04', editable=False),
        ),
    ]
