# Generated by Django 4.1.3 on 2023-02-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti_sadhna_api', '0009_alter_otp_count_alter_otp_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='in_time',
            field=models.TimeField(default='04:18:28', editable=False),
        ),
    ]
